name: rps
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - cudatoolkit
  - python
  - pip
  - torchaudio
  - torchvision
  - pip:
    - tqdm
    - opencv-python
    - tensorboard=2.12.0